In [14]:
import matplotlib.pyplot as plt
import pennylane as qml
import scipy as sp

from pennylane import numpy as np
from IPython.display import display, Math

np.set_printoptions(threshold=np.inf, linewidth=np.inf)
np.set_printoptions()

# == Pre_defined state ==
pauli_x = np.array([ [0, 1], [1, 0]])
pauli_y = np.array([ [0, -1.j], [1.j, 0]])
pauli_z = np.array([ [1, 0], [0, -1]])

# state = (00 + 01 + 10 + 11)/2 = kron(|0> + |1>)/sqrt(2) , (|0> + |1>)/sqrt(2) )
state_super_pos = np.kron( (np.array([[1], [0]]) + np.array([[0], [1]]))/np.sqrt(2) , (np.array([[1], [0]]) + np.array([[0], [1]]))/np.sqrt(2) )
rho_super_pos = np.kron(state_super_pos, state_super_pos.conj().T) 
# state_super_pos, state_super_pos.con().T has different dimension 


# bell state = (|00> + |11>) / sqrt(2)
state_bell_1 = ( np.kron( np.array([ [1], [0] ]) , np.array([ [1], [0] ]) ) +  np.kron( np.array([ [0], [1] ]) , np.array([ [0], [1] ]) ) )/np.sqrt(2) 
rho_bell_1 = np.kron(state_bell_1 , state_bell_1.conj().T)

state_bell_2 = ( np.kron( np.array([ [1], [0] ]) , np.array([ [1], [0] ]) ) -  np.kron( np.array([ [0], [1] ]) , np.array([ [0], [1] ]) ) )/np.sqrt(2) 
rho_bell_2 = np.kron(state_bell_2 , state_bell_2.conj().T)

state_bell_3 = ( np.kron( np.array([ [1], [0] ]) , np.array([ [0], [1] ]) ) +  np.kron( np.array([ [0], [1] ]) , np.array([ [1], [0] ]) ) )/np.sqrt(2) 
rho_bell_3 = np.kron(state_bell_3 , state_bell_3.conj().T)

state_bell_4 = ( np.kron( np.array([ [1], [0] ]) , np.array([ [0], [1] ]) ) -  np.kron( np.array([ [0], [1] ]) , np.array([ [1], [0] ]) ) )/np.sqrt(2)  
rho_bell_4 = np.kron(state_bell_4 , state_bell_4.conj().T)


print('bell_state_1:\n',rho_bell_1,'\n')
print('bell_state_2:\n',rho_bell_2,'\n')
print('bell_state_3:\n',rho_bell_3,'\n')
print('bell_state_4:\n',rho_bell_4,'\n')

bell_state_1:
 [[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]] 

bell_state_2:
 [[ 0.5  0.   0.  -0.5]
 [ 0.   0.   0.  -0. ]
 [ 0.   0.   0.  -0. ]
 [-0.5 -0.  -0.   0.5]] 

bell_state_3:
 [[0.  0.  0.  0. ]
 [0.  0.5 0.5 0. ]
 [0.  0.5 0.5 0. ]
 [0.  0.  0.  0. ]] 

bell_state_4:
 [[ 0.   0.  -0.   0. ]
 [ 0.   0.5 -0.5  0. ]
 [-0.  -0.5  0.5 -0. ]
 [ 0.   0.  -0.   0. ]] 

