In [75]:
import pennylane as qml
from pennylane import numpy as np

import matplotlib.pyplot as plt

gamma = 0
t = 0


dev = qml.device("default.qubit", wires=1)
@qml.qnode(dev)
def circuit(phi):
    qml.Hadamard(wires=0)
    
    qml.RZ(phi, wires=0)
    qml.RZ(t, wires=0)
    
    qml.Hadamard(wires=0)
    
    data = qml.density_matrix(wires=0)  
    
    return data 

def kraus(rho): 
    k = np.array([[np.sqrt(1-gamma), 0], [0, 1]])
    rho_ps = (k @ rho @ k.conj().T) / np.trace(k @ k.conj().T * rho)
    
    return rho_ps



In [76]:
circuit(np.pi)

tensor([[3.74939946e-33+0.000000e+00j, 0.00000000e+00+6.123234e-17j],
        [0.00000000e+00-6.123234e-17j, 1.00000000e+00+0.000000e+00j]], requires_grad=True)

In [77]:
#  == Plot for CFI ==
N = 1000
tau_CFI = np.linspace(-0.001, 6.3, N)

CFI = np.zeros(N)
# CFI_numpy[0] = CFI(tau_CFI[0])

# CFI_numpy

# CFI -> Approcach with array index
for i in range(len(tau_CFI)):
     CFI[i] = qml.qinfo.classical_fisher(kraus(circuit))(tau_CFI[i])

# CFI_numpy[i] = (qml.qinfo.classical_fisher(circuit)(tau_CFI[i]))
#     # Casting to numpy array without gradient
#     CFI_numpy[i] = round((CFI_numpy[i]).numpy(), 10)

plt.subplot()
plt.plot(tau_CFI, CFI)
plt.title('CFI')
plt.xlabel('Time')
plt.ylabel('Probability_0_state')
# plt.legend()
plt.grid()

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

[[3.74939946e-33+0.000000e+00j 0.00000000e+00+6.123234e-17j]
 [0.00000000e+00-6.123234e-17j 1.00000000e+00+0.000000e+00j]] 

 [[ 0.-0.000000e+00j -0.-6.123234e-17j]
 [-0.+6.123234e-17j  1.-0.000000e+00j]]


tensor([[ True,  True],
        [ True,  True]], requires_grad=True)

In [ ]:
# def rho_ps(phi):

# 	rho_ps = np.array([ [(gamma - 1 )*(np.exp(t) + np.cos(phi)), 1.j*np.sqrt(1-gamma)*np.sin(phi) ], [-1.j*np.sqrt(1-gamma)*np.sin(phi), np.cos(phi) - np.exp(t)] ]) / (gamma * np.cos(phi) + (gamma - 2) * np.exp(t))
# 	return rho_ps


# def rho(phi, t):
#     result = np.array([ [1+np.exp(-t)*np.cos(phi), -1.j*np.exp(-t)*np.sin(phi)], [1.j*np.exp(-t)*np.sin(phi), 1-np.exp(-t)*np.cos(phi)] ]) / 2
    
#     return result

# rho(np.pi, 0)


# np.isclose(circuit(np.pi, 0), rho(np.pi, 0))

tensor([[ True,  True],
        [ True,  True]], requires_grad=True)