In [15]:
import numpy as np
import scipy as sp

pauli_y = np.array([ [0, -1.j], [1.j, 0]])

# state vector of bell state
bell_state = (np.kron( np.array([ [1], [0] ]), np.array([ [1], [0] ])) + np.kron( np.array([ [0], [1] ]), np.array([ [0], [1] ])))/np.sqrt(2)

print('bell state:\n',bell_state,'\n')

rho = bell_state @ bell_state.conj().T

print('rho_bell:\n',rho,'\n')

def rho_total():
    
    # rho_tot = (np.kron( np.array([ [1], [0] ]), np.array([ [1], [0] ])) + np.kron( np.array([ [1], [0] ]), np.array([ [0], [1] ])) + np.kron( np.array([ [0], [1] ]), np.array([ [1], [0] ])) + np.kron( np.array([ [0], [1] ]), np.array([ [0], [1] ])))/2
    rho_tot = np.kron( (np.array([ [1], [0]]) + np.array([ [0], [1]]))/np.sqrt(2) , (np.array([ [1], [0]]) + np.array([ [0], [1]]))/np.sqrt(2))
     
    return rho_tot


def concurrence_calculation(rho):
 
	# density matrix casting to numpy

	rho_uni = np.kron(pauli_y, pauli_y) @ rho.conj() @ np.kron(pauli_y, pauli_y)
	
	R = sp.linalg.sqrtm( sp.linalg.sqrtm(rho) @ rho_uni @ sp.linalg.sqrtm(rho) )
	# print('Concurrence matrix(R): \n', R)

	# sort array in descending order
	eig_vals = np.sort(sp.linalg.eigvals(R).real)[::-1]
	# print('Eig_val descending order:', eig_vals)

	concurrence = np.amax([ 0, (2*eig_vals[0] - np.sum(eig_vals)) ])	
	# concurrence = 0 vs (2*eig_vals[0] - np.sum(eig_vals)) which is bigger?
	# print('np.amax:', -concurrence)


	# 1-concurrence = minimum => concurrence = max!!
	return concurrence


print('rho_tot:\n', rho_total(),'\n')

den_tot = rho_total() @ rho_total().conj().T

print('\n', den_tot)

print('concurrence:\n',concurrence_calculation(rho))
print('concurrence:\n',concurrence_calculation(den_tot))

bell state:
 [[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]] 

rho_bell:
 [[0.5 0.  0.  0.5]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.5 0.  0.  0.5]] 

rho_tot:
 [[0.5]
 [0.5]
 [0.5]
 [0.5]] 


 [[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
concurrence:
 0.9999999999999998
concurrence:
 0.0
