In [107]:
import numpy as np


In [108]:
import numpy as np

# Create the 3D array filled with zeros
array = np.zeros((2, 2, 2))

# Create array_1
array_1 = np.array([1, 1]).reshape(-1, 1)

# # Reshape array_1 to match the shape of array
# array_1_reshaped = array_1.reshape(2, 1, 1)

# # Stack array and array_1 horizontally
# result = np.hstack((array, array_1_reshaped))

# # Print the result
# print(result)


In [109]:
data = 0
for i in range(3):
    data = 4 if i == 2 else 1
    print('dd')


dd
dd
dd


In [110]:
array[:, :, 0] = array_1

array

array([[[1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.]]])

In [111]:
tt = np.array([1,2,3,4,5,6])

tt

array([1, 2, 3, 4, 5, 6])

In [114]:
def SLSQP(Sweep_Data, paras, gamma_ps_select, Iterations):
    # Create Data array
    PHI = np.arange(Sweep_Data[0], Sweep_Data[1], Sweep_Data[2]).reshape(-1, 1)
    
    # PHI = 95,1
    
    # Before append with PHI col = 7-col
    Data = np.zeros((Iterations, len(PHI), len(paras) + 1))
    
    # 0_col => PHI
    # Data[:][:, 0] = PHI
    
    return Data


# == Fixed to gamma_ps = 0.8 ==
# == Sweep for 0 ~ pi*3 == 
Sweep_data = np.array([1e-3, np.pi * 1/2 + 1e-3, 1e-1])
Para_init = np.array([1, 1, 1, 1e-1, 1e-1, 1e-1])
Gamma_ps_preset = 0.8
Iterations_set = 2

Optimized_Result = SLSQP(Sweep_data, Para_init, Gamma_ps_preset, Iterations_set)

In [134]:
temp_11 = np.zeros((3,3))

temp_11

test_3 = np.ones((3,1))

test_3

np.concatenate((test_3, temp_11), axis=1)

array([[1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [147]:
# == SLSQP -> Return Data_set:[phi, CFI, 6-Paras] ==
def SLSQP(Sweep_Data, paras, gamma_ps_select, Iterations):
    # Create Data array
    PHI = np.arange(Sweep_Data[0], Sweep_Data[1], Sweep_Data[2]).reshape(-1, 1)
    
    # Before append with PHI col = 7-col
    #  fixed 1 -> 2
    Data = np.zeros((Iterations, len(PHI), len(paras) + 2))
    # 0_col => PHI
    # Data[:, :, 0] = PHI
    # Data[:][:,0] = PHI
    
    Data[:, :, 0] = PHI.squeeze()
    
    
    return Data


# == Fixed to gamma_ps = 0.8 ==
# == Sweep for 0 ~ pi*3 == 
Sweep_data = np.array([1e-3, np.pi * 3 + 1e-3, 1e-1])
Para_init = np.array([1, 1, 1, 1e-1, 1e-1, 1e-1])
Gamma_ps_preset = 0.8
Iterations_set = 2

Optimized_Result = SLSQP(Sweep_data, Para_init, Gamma_ps_preset, Iterations_set)

Optimized_Result[1][:, 0].reshape(-1,1)

array([[1.000e-03],
       [1.010e-01],
       [2.010e-01],
       [3.010e-01],
       [4.010e-01],
       [5.010e-01],
       [6.010e-01],
       [7.010e-01],
       [8.010e-01],
       [9.010e-01],
       [1.001e+00],
       [1.101e+00],
       [1.201e+00],
       [1.301e+00],
       [1.401e+00],
       [1.501e+00],
       [1.601e+00],
       [1.701e+00],
       [1.801e+00],
       [1.901e+00],
       [2.001e+00],
       [2.101e+00],
       [2.201e+00],
       [2.301e+00],
       [2.401e+00],
       [2.501e+00],
       [2.601e+00],
       [2.701e+00],
       [2.801e+00],
       [2.901e+00],
       [3.001e+00],
       [3.101e+00],
       [3.201e+00],
       [3.301e+00],
       [3.401e+00],
       [3.501e+00],
       [3.601e+00],
       [3.701e+00],
       [3.801e+00],
       [3.901e+00],
       [4.001e+00],
       [4.101e+00],
       [4.201e+00],
       [4.301e+00],
       [4.401e+00],
       [4.501e+00],
       [4.601e+00],
       [4.701e+00],
       [4.801e+00],
       [4.901e+00],


In [146]:
PHI = np.arange(1e-3, np.pi * 3 + 1e-3, 1e-1).reshape(-1, 1)

PHI

array([[1.000e-03],
       [1.010e-01],
       [2.010e-01],
       [3.010e-01],
       [4.010e-01],
       [5.010e-01],
       [6.010e-01],
       [7.010e-01],
       [8.010e-01],
       [9.010e-01],
       [1.001e+00],
       [1.101e+00],
       [1.201e+00],
       [1.301e+00],
       [1.401e+00],
       [1.501e+00],
       [1.601e+00],
       [1.701e+00],
       [1.801e+00],
       [1.901e+00],
       [2.001e+00],
       [2.101e+00],
       [2.201e+00],
       [2.301e+00],
       [2.401e+00],
       [2.501e+00],
       [2.601e+00],
       [2.701e+00],
       [2.801e+00],
       [2.901e+00],
       [3.001e+00],
       [3.101e+00],
       [3.201e+00],
       [3.301e+00],
       [3.401e+00],
       [3.501e+00],
       [3.601e+00],
       [3.701e+00],
       [3.801e+00],
       [3.901e+00],
       [4.001e+00],
       [4.101e+00],
       [4.201e+00],
       [4.301e+00],
       [4.401e+00],
       [4.501e+00],
       [4.601e+00],
       [4.701e+00],
       [4.801e+00],
       [4.901e+00],


In [148]:
paras = np.array([1,1,1,1,1,1])
