In [3]:
import matplotlib.pyplot as plt
import numpy as np

from qutip import *

q = Qobj([ [1], [0] ])

q

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]

In [4]:
sz = Qobj([ [1, 0], [0, -1] ])
sy = Qobj([ [0, -1.j], [1.j, 0] ])

Hamiltonian = 1.0 * sz + 0.1 * sy

Hamiltonian

sy.eigenenergies()

array([-1.,  1.])

In [5]:
basis(2, 0)


Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[1.]
 [0.]]