In [1]:
import numpy as np

# z,y,x
array_2d = np.arange(1,11).reshape(2,5)
array_3d = np.arange(1,21).reshape(2,2,5)


print(array_2d,'\n\n == \n')
print(array_3d,'\n\n == \n')

# 가장 상위 axis 
print( np.mean(array_2d,axis = 0), '\n' )
print( np.mean(array_3d,axis = 0) ,'\n'  )
#  z axis


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

 == 

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]] 

 == 

[3.5 4.5 5.5 6.5 7.5] 

[[ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]] 

