In [1]:
import numpy as np

In [24]:
array = np.arange(0, 3, 1)

array

array([0, 1, 2])

In [25]:
array[:-1]

array([0, 1])

In [19]:
array[-1:]

array([2])

In [28]:
from itertools import product

for idx in product(range(2), repeat=len(array)):
    print(array+list(idx))
    print()

[0 1 2]

[0 1 3]

[0 2 2]

[0 2 3]

[1 1 2]

[1 1 3]

[1 2 2]

[1 2 3]

